### ISSUE TITLE
vagrant up won't complete

### ISSUE THREAD

**Issue by barisdemiray** [xeraa/vagrant-elastic-stack#14]
Hello,

I got an error while doing `vagrant up` and it's pretty mysterious for me.

> TASK [Add osquery's server repository] *****************************************
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The repository 'https://osquery-packages.s3.amazonaws.com/bionic bionic Release' does not have a Release file.
> fatal: [ubuntu]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Gqglog/ansible_module_apt_repository.py\", line 551, in <module>\n    main()\n  File \"/tmp/ansible_Gqglog/ansible_module_apt_repository.py\", line 543, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 543, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:The repository 'https://osquery-packages.s3.amazonaws.com/bionic bionic Release' does not have a Release file.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
> 	to retry, use: --limit @/elastic-stack/0_install.retry
> 
> PLAY RECAP *********************************************************************
> ubuntu                     : ok=20   changed=13   unreachable=0    failed=1   
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.
> 

Then I tried again, but I was suggested to run `vagrant provision` this time. I did so, only to have the same error in a more brief way,

> TASK [Install the JRE] *********************************************************
> fatal: [ubuntu]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'https://osquery-packages.s3.amazonaws.com/bionic bionic Release' does not have a Release file."}
> 	to retry, use: --limit @/elastic-stack/0_install.retry
> 
> PLAY RECAP *********************************************************************
> ubuntu                     : ok=8    changed=1    unreachable=0    failed=1   
> 

Sorry for posting before doing any research, I wanted to check if it has a quick fix since the workshop is tomorrow.

Thanks!

**Comment by Minmm2017** [comment]
Hi, I am the same problem as you. I tried to downgrade Ubuntu as you point out, but it still does not work...

**Comment by barisdemiray** [comment]
Any error messages?

**Comment by barisdemiray** [comment]
You're right. Downgrading works only under Windows but under Ubuntu 18.04 I have this,

> fatal: [ubuntu]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key adv --keyserver keyserver.ubuntu.com --recv 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B", "msg": "Error fetching key 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B from keyserver: keyserver.ubuntu.com", "rc": 2, "stderr": "gpg: requesting key C9D8B80B from hkp server keyserver.ubuntu.com\ngpg: keyserver timed out\ngpg: keyserver receive failed: keyserver error\n", "stderr_lines": ["gpg: requesting key C9D8B80B from hkp server keyserver.ubuntu.com", "gpg: keyserver timed out", "gpg: keyserver receive failed: keyserver error"], "stdout": "Executing: /tmp/tmp.apPXOiz28x/gpg.1.sh --keyserver\nkeyserver.ubuntu.com\n--recv\n1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B\n", "stdout_lines": ["Executing: /tmp/tmp.apPXOiz28x/gpg.1.sh --keyserver", "keyserver.ubuntu.com", "--recv", "1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B"]}
> 	to retry, use: --limit @/elastic-stack/0_install.retry
> 
> PLAY RECAP *********************************************************************
> ubuntu                     : ok=19   changed=12   unreachable=0    failed=1   
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.
>

**Comment by xeraa** [comment]
I'm sorry, I didn't properly test this. The problem is that osquery doesn't seem to have a dedicated Bionic package, but there is a generic DEB one I'm using instead now (see the commit above).

**Comment by AlienPie** [comment]
This was still broken for me in the latest release. I doscovered it's an issue with the keyserver command for osquery.

```
TASK [Add osquery's repository key] ********************************************
fatal: [ubuntu]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key adv --keyserver keyserver.ubuntu.com --recv 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B", "msg": "Error fetching key 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B from keyserver: keyserver.ubuntu.com", "rc": 2, "stderr": "gpg: requesting key C9D8B80B from hkp server keyserver.ubuntu.com\ngpg: no valid OpenPGP data found.\ngpg: Total number processed: 0\ngpg: keyserver communications error: keyserver unreachable\ngpg: keyserver communications error: public key not found\ngpg: keyserver receive failed: public key not found\n", "stderr_lines": ["gpg: requesting key C9D8B80B from hkp server keyserver.ubuntu.com", "gpg: no valid OpenPGP data found.", "gpg: Total number processed: 0", "gpg: keyserver communications error: keyserver unreachable", "gpg: keyserver communications error: public key not found", "gpg: keyserver receive failed: public key not found"], "stdout": "Executing: /tmp/tmp.06bmq6cOla/gpg.1.sh --keyserver\nkeyserver.ubuntu.com\n--recv\n1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B\n?: keyserver.ubuntu.com: Connection refused\ngpgkeys: HTTP fetch error 7: couldn't connect: Connection refused\n", "stdout_lines": ["Executing: /tmp/tmp.06bmq6cOla/gpg.1.sh --keyserver", "keyserver.ubuntu.com", "--recv", "1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B", "?: keyserver.ubuntu.com: Connection refused", "gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused"]}
        to retry, use: --limit @/elastic-stack/0_install.retry
```

I was able to solve this by modifying line 101 of `0_install.yml`

` - keyserver: keyserver.ubuntu.com`
` + keyserver: hkp://keyserver.ubuntu.com:80`

Seemed to be some issue with verifying the public key of the server.
