### ISSUE TITLE
Can't run all.sh

### ISSUE THREAD

**Issue by kyrillos52** [xeraa/vagrant-elastic-stack#15]
Hello,

I had an error at the end of running vagrant up (forgot to copy the issue) but had a successful message as well.

Now, when I try run /elastic-stack/all.sh, I have this issue.

vagrant@elastic-stack:~$ /elastic-stack/all.sh
-bash: /elastic-stack/all.sh: /bin/bash^M: bad interpreter: No such file or directory

Do you have a quick solution ?

Thank you,

Cyril

**Comment by barisdemiray** [comment]
Scripts under /elastic-stack have Windows line-endings. To fix it,

    $ vi /elastic-stack/all.sh

and inside VIM, issue the command, by first typing a :

    set ff=unix
