### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tacowart** [xeraa/vagrant-elastic-stack#21]
This is a great example of building an elastic stack in a VM. I just have one question regarding the x-pack implementation. How do I log in to kibana with this up? I looked in the files and it looks like a variable was assigned {{kibana_user_password}}. But I can't really seem to get it done. Granted I'm a newbie at elk and I was planning on using this to ingest some old logs for a project to visualize the data with kibana. SOS.

**Comment by tacowart** [comment]
Never mind I figured it out. Sorry to bug you!

**Comment by xeraa** [comment]
If this is resolved, then good. I've also commented on the other issue :)
