### ISSUE TITLE
Kibana doesn't work

### ISSUE THREAD

**Issue by Tom60chat** [xeraa/vagrant-elastic-stack#22]
Hello,
I wanted to try the OVA Image, but I can't access kibana.

- I download the OVA
- Put in VirtualBox
- Start it
- And i wrote:
`curl https://127.0.0.1:5601`

I got:
![image](https://user-images.githubusercontent.com/25564492/191745088-a9599804-08f9-4bd1-afaa-d9393162ce6d.png)

**Comment by xeraa** [comment]
This is super old. I would recommend to use a Docker Compose setup with a current version.

For getting this up and running, what's in `/var/log/kibana/kibana.log`?

**Comment by Tom60chat** [comment]
Yeah, I just wanted to have a way to test if ELK Stack was good enough for me.

The file is pretty big, so i'm upload it here :
[kibana.log](https://github.com/xeraa/vagrant-elastic-stack/files/9634333/kibana.log)

**Comment by xeraa** [comment]
Looks like Kibana is trying to Elasticsearch on http://localhost:9200 but that should be HTTP**S**?

And to see if it's good enough: This is 3 years old — I don't think that's giving you a great picture. If you mostly want to see it in action, I'd recommend https://demo.elastic.co. If you want to start it locally, then https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file

**Comment by Tom60chat** [comment]
I didn't know about demo.elastic.com, thanks I will use that.
