### ISSUE TITLE
Kibana prompt to enter password

### ISSUE THREAD

**Issue by poornalingam** [xeraa/vagrant-elastic-stack#3]
In Mac, after success full installation. Kibana login page is popping up. As per the document it should prompt to select the default Index. On configuring user name and password in kibana.yml file the system throws elastic licensing error. Please add the default user name and password in documents.  

Able to login with  elastic/changeme in Kibana but the rest of components (logstash, beats) are unable to establish the connection.

Here is a error message
root@vagrant-ubuntu-trusty-32:/var/log/elasticsearch# curl http://localhost:9200/
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}root@vagrant-ubuntu-trusty-32:/var/log/elasticsearch# curl http://localhost:9200/
{ 

Port 9200 and 9300 are not running tcp 4
vagrant@vagrant-ubuntu-trusty-32:~/.ssh$ netstat -lt |egrep '9200|9300|5601'
tcp        0      0 *:5601                  *:*                     LISTEN     
tcp6       0      0 localhost:9300          [::]:*                  LISTEN     
tcp6       0      0 ip6-localhost:9300      [::]:*                  LISTEN     
tcp6       0      0 ip6-localhost:5601      [::]:*                  LISTEN     
tcp6       0      0 localhost:9200          [::]:*                  LISTEN     
tcp6       0      0 ip6-localhost:9200      [::]:*                  LISTEN

**Comment by xeraa** [comment]
That's X-Pack, I'll fix this. Skip the final step to run without security in the meantime.

Thanks for reporting!

**Comment by xeraa** [comment]
Hi @poornalingam,

I've just pushed a fix for Logstash, the Beats and added some documentation. Let me know if stuff still does not work as expected :)
