### ISSUE TITLE
Tried the recepie on a fresh 16.04 LTS and got this issue; all prerequisites were installed via apt-get

### ISSUE THREAD

**Issue by bubba198** [xeraa/vagrant-elastic-stack#6]
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

**Comment by xeraa** [comment]
I'm sorry if this was confusing, but you will need a Vagrant provider — Virtualbox is strongly recommended. I've added a note in the readme. Please let me know if this is still unclear.
